import { RetrievedKnowledgeItem } from '../types/environmental';

export const ENVIRONMENTAL_KNOWLEDGE_BASE: RetrievedKnowledgeItem[] = [
  {
    id: 'KB-FAO-SOC-01',
    title: 'Soil Organic Carbon and Available Water Capacity in Semi-Arid Croplands',
    topic: 'Soil organic carbon & Water retention',
    environmentalVariables: ['soil organic carbon', 'soil moisture', 'rainfall', 'water availability'],
    ecosystem: 'Semi-arid agroecosystem',
    region: 'Global / Drylands',
    condition: 'Low soil organic carbon (<1.0%), low rainfall (<400mm), acute water deficit',
    mechanism: 'Each 1% increase in mass soil organic carbon expands available water capacity (AWC) by 1.5% to 3.7% volumetric moisture depending on soil texture, stabilizing the rhizosphere moisture buffer against prolonged inter-storm dry periods.',
    expectedEffect: 'Elevates plant-available soil moisture by 15-28mm in the top 30cm root zone, buffering root-associated microbiological communities and mycorrhizal diversity against moisture shocks.',
    timeHorizon: 'Medium term (3-7 years)',
    evidence: 'FAO Global Soil Partnership Technical Report on Recarbonizing Global Soils (2020); Minasny & McBratney (2018), Geoderma.',
    source: 'FAO (Food and Agriculture Organization of the United Nations)',
    sourceUrl: 'https://www.fao.org/global-soil-partnership/resources/en/',
    year: 2020,
    reliability: 'Global UN/FAO Assessment',
    confidence: 'High',
    tags: ['soil health', 'soil organic carbon', 'water retention', 'semi-arid', 'drought resilience']
  },
  {
    id: 'KB-IPCC-AGROFORESTRY-02',
    title: 'Agroforestry and Multi-Strata Buffers in Water-Stressed Semi-Arid Systems',
    topic: 'Agroforestry & Microclimate moderation',
    environmentalVariables: ['temperature', 'rainfall', 'species richness', 'habitat diversity', 'land use'],
    ecosystem: 'Dryland and semi-arid cropping systems',
    region: 'Semi-arid / Mediterranean / Sub-Saharan',
    condition: 'High thermal stress (>30°C), monoculture annual grain, low wild habitat heterogeneity',
    mechanism: 'Deep-rooting woody perennials facilitate hydraulic lift of subsoil moisture to shallow strata, while tree canopies reduce ground-level wind speeds, suppress evapotranspirational losses by 20-35%, and lower canopy surface temperature by 2-5°C.',
    expectedEffect: 'Generates multi-tiered structural microhabitats supporting insect predators, avian functional guilds, and beneficial soil nematodes while stabilizing grain yields.',
    timeHorizon: 'Medium to Long term (4-10 years)',
    evidence: 'IPCC Special Report on Climate Change and Land (SRCCL), Chapter 5: Food Security (2019); ICRAF Agroforestry Compendium.',
    source: 'IPCC (Intergovernmental Panel on Climate Change)',
    sourceUrl: 'https://www.ipcc.ch/srccl/',
    year: 2019,
    reliability: 'IPCC Assessment Report',
    confidence: 'High',
    tags: ['agroforestry', 'temperature stress', 'habitat diversity', 'hydraulic lift', 'climate resilience']
  },
  {
    id: 'KB-NATURE-COVERCROPS-03',
    title: 'Leguminous and Polyculture Cover Crops for Carbon Sequestration and Soil Microbiome',
    topic: 'Cover crops & Soil biology',
    environmentalVariables: ['soil organic carbon', 'soil pH', 'soil health', 'species richness', 'land use'],
    ecosystem: 'Temperate and dryland agroecosystems',
    region: 'Global temperate and dry Mediterranean regions',
    condition: 'Continuous monoculture wheat/cereal with bare fallow periods and depleted topsoil carbon (<0.6%)',
    mechanism: 'Multi-species cover crops provide continuous living root exudates (sugars, amino acids), feeding arbuscular mycorrhizal fungi and nitrogen-fixing bacteria, converting root carbon into stabilized mineral-associated organic matter (MAOM).',
    expectedEffect: 'Increases topsoil organic carbon stocks by ~0.32-0.55 Mg C/ha/year while enhancing soil microbial active biomass by 25-40% and pollinator floral resource availability.',
    timeHorizon: 'Short to Medium term (2-5 years)',
    evidence: 'Poeplau & Don (2015) meta-analysis in Agriculture, Ecosystems & Environment; Bowles et al. (2020), Nature Communications.',
    source: 'Peer-reviewed Meta-analysis (Agric. Ecosyst. Environ. & Nature Comms)',
    sourceUrl: 'https://doi.org/10.1016/j.agee.2014.10.024',
    year: 2020,
    reliability: 'Peer-reviewed Meta-analysis',
    confidence: 'High',
    tags: ['cover crops', 'soil carbon', 'microbial diversity', 'monoculture mitigation', 'pollinators']
  },
  {
    id: 'KB-IUCN-HABITATSTRIPS-04',
    title: 'Native Floral and Shrub Field-Border Corridors for Invertebrate Biodiversity',
    topic: 'Native vegetation & Habitat fragmentation',
    environmentalVariables: ['habitat diversity', 'species richness', 'land use', 'deforestation_habitat_loss'],
    ecosystem: 'Agricultural landscapes and converted wildlands',
    region: 'Global agricultural belts',
    condition: 'Homogenized agricultural landscape with field sizes >20 ha, low floral diversity',
    mechanism: 'Non-cropped perennial strips of indigenous drought-adapted flowering forbs and shrubs provide nesting substrates, continuous pollen/nectar resources, and structural overwintering refugia for arthropod parasitoids and solitary bees.',
    expectedEffect: 'Multiplies wild pollinator abundance by 2.2x to 4x within 150m of borders, increases beneficial predator functional diversity, and creates stepping-stone corridors bridging fragmented natural fragments.',
    timeHorizon: 'Short term (1-3 years)',
    evidence: 'IUCN Nature-Based Solutions Standard (2020); Garibaldi et al. (2016), Science: Mutually beneficial pollinator services.',
    source: 'IUCN (International Union for Conservation of Nature)',
    sourceUrl: 'https://www.iucn.org/our-work/nature-based-solutions',
    year: 2020,
    reliability: 'IUCN Conservation Guidelines',
    confidence: 'High',
    tags: ['native vegetation', 'habitat fragmentation', 'pollinators', 'beneficial insects', 'corridors']
  },
  {
    id: 'KB-CGIAR-INTERCROPPING-05',
    title: 'Strip Intercropping and Cereal-Legume Relays in Low-Moisture Soils',
    topic: 'Intercropping & Ecosystem resilience',
    environmentalVariables: ['land use', 'soil health', 'soil moisture', 'species richness', 'rainfall'],
    ecosystem: 'Semi-arid and sub-humid cropping systems',
    region: 'Dryland Mediterranean, Western Australia, and Great Plains',
    condition: 'Continuous monoculture cereal cropping, low soil nitrogen, variable seasonal rainfall',
    mechanism: 'Spatial juxtaposition of deep-taproot legumes (e.g. chickpea, pigeonpea) with shallow fibrous-root cereals partitions subterranean water and nutrient niches while interrupting pest and fungal pathogen life cycles.',
    expectedEffect: 'Yield stability index rises by 18-30% in drought-stress years; reduces synthetic nitrogen demand by 30-50 kg N/ha and fosters epigeal beetle and spider predator richness.',
    timeHorizon: 'Short term (1-2 agricultural seasons)',
    evidence: 'CGIAR Dryland Systems Program; Raseduzzaman & Jensen (2017), Agronomy for Sustainable Development.',
    source: 'CGIAR / Research Program on Dryland Systems',
    sourceUrl: 'https://www.cgiar.org/research/program-platform/drylands/',
    year: 2018,
    reliability: 'CGIAR/ICRAF Research Report',
    confidence: 'High',
    tags: ['intercropping', 'cereal legume', 'niche partitioning', 'pest suppression', 'soil fertility']
  },
  {
    id: 'KB-UNEP-DEGRADATION-06',
    title: 'Combating Desertification and Soil Salinization in Arid Farmlands',
    topic: 'Soil pH, Salinity & Desertification',
    environmentalVariables: ['soil pH', 'soil moisture', 'water availability', 'temperature', 'soil health'],
    ecosystem: 'Arid and semi-arid irrigated or rainfed croplands',
    region: 'Dryland basins, Australasia, Mediterranean, Central Asia',
    condition: 'Elevated soil pH (>8.0) or electrical conductivity, shallow saline groundwater, high evapotranspiration',
    mechanism: 'High evaporation relative to precipitation wicks dissolved alkaline salts upward. Incorporating organic composts and planting deep-rooted halophytic or salt-tolerant perennial grasses increases infiltration and suppresses capillary evaporative crusting.',
    expectedEffect: 'Mitigates surface salt accumulation, stabilizes rhizosphere pH toward neutral (6.5-7.5), and revives sensitive nitrifying bacterial populations.',
    timeHorizon: 'Medium term (3-5 years)',
    evidence: 'UNEP Global Environment Outlook (GEO-6); FAO Status of the World\'s Soil Resources (2015).',
    source: 'UNEP (United Nations Environment Programme)',
    sourceUrl: 'https://www.unep.org/resources/global-environment-outlook-6',
    year: 2019,
    reliability: 'Global UN/FAO Assessment',
    confidence: 'Medium',
    tags: ['soil pH', 'salinization', 'desertification', 'rhizosphere', 'organic amendments']
  },
  {
    id: 'KB-SCIENCE-PESTREG-07',
    title: 'Conservation Biological Control via Landscape Heterogeneity and Semi-Natural Patches',
    topic: 'Human impact, Pesticide reduction & Food web stability',
    environmentalVariables: ['pollution level', 'habitat diversity', 'species richness', 'land use'],
    ecosystem: 'Intensive cropland and mixed rural zones',
    region: 'Global',
    condition: 'Heavy chemical pesticide input, simplified crop mosaic, low natural enemy population',
    mechanism: 'Landscape simplification removes non-crop habitats essential for parasitoid wasps, ladybird beetles, and hoverflies. Retaining >20% semi-natural patches suppresses herbivorous pest populations below economic thresholds without broad-spectrum chemical sprays.',
    expectedEffect: 'Lowers chemical pesticide reliance by 40-70%, directly reducing soil and surface water ecotoxicity while recovering aquatic and soil micro-arthropod communities.',
    timeHorizon: 'Medium term (2-4 years)',
    evidence: 'Dainese et al. (2019), Science Advances: A global synthesis reveals biodiversity-mediated ecosystem services in crops.',
    source: 'Peer-reviewed Meta-analysis (Science Advances)',
    sourceUrl: 'https://doi.org/10.1126/sciadv.aax0121',
    year: 2019,
    reliability: 'Peer-reviewed Meta-analysis',
    confidence: 'High',
    tags: ['pollution', 'pesticide reduction', 'biological control', 'landscape heterogeneity', 'food web']
  },
  {
    id: 'KB-RAMSAR-WETLAND-08',
    title: 'Riparian Buffer Zones and Vegetated Swales for Agricultural Runoff Filtration',
    topic: 'Water quality, Riparian buffers & Aquatic biodiversity',
    environmentalVariables: ['water availability', 'pollution level', 'species richness', 'soil moisture'],
    ecosystem: 'Riparian zones, drainage swales, and alluvial valleys',
    region: 'Global agricultural river basins',
    condition: 'High agricultural nitrate/phosphate runoff, degraded stream banks, low aquatic species richness',
    mechanism: 'Multi-tiered riparian buffers (native trees, shrubs, and dense sedge/grass filters) physically trap eroded particulate sediment and facilitate microbiological denitrification in shallow groundwater zones.',
    expectedEffect: 'Filters 60-90% of suspended sediment and 40-75% of dissolved nitrogen before reaching open water bodies, regenerating macroinvertebrate and freshwater fish spawning zones.',
    timeHorizon: 'Short to Medium term (2-5 years)',
    evidence: 'Ramsar Convention on Wetlands Scientific & Technical Review; Stutter et al. (2012), J. Environ. Qual.',
    source: 'Ramsar Convention on Wetlands & UNEP',
    sourceUrl: 'https://www.ramsar.org/resources/documents',
    year: 2018,
    reliability: 'Global UN/FAO Assessment',
    confidence: 'High',
    tags: ['water quality', 'riparian buffers', 'runoff filtration', 'wetland restoration', 'aquatic biodiversity']
  },
  {
    id: 'KB-PNAS-FORESTREST-09',
    title: 'Assisted Natural Regeneration (ANR) and Rewilding Degraded Forest Edges',
    topic: 'Deforestation, Forest restoration & Keystone species',
    environmentalVariables: ['deforestation_habitat_loss', 'habitat diversity', 'species richness', 'temperature'],
    ecosystem: 'Tropical and temperate fragmented woodlands',
    region: 'Deforested tropical and sub-tropical margins',
    condition: 'Heavy deforestation (>50% forest cover lost), edge desiccation, isolated forest fragments',
    mechanism: 'Assisted natural regeneration removes invasive grasses and protects remnant pioneer tree seedlings, re-establishing forest canopy closure faster and more resiliently than single-species tree plantations.',
    expectedEffect: 'Recovers structural forest vertical complexity, stabilizes microclimatic vapor pressure deficit, and enables recolonization of native understory bird and mammal species.',
    timeHorizon: 'Long term (5-15 years)',
    evidence: 'Chazdon et al. (2020), PNAS: Secondary forests and ecological restoration pathways.',
    source: 'Peer-reviewed Meta-analysis (PNAS)',
    sourceUrl: 'https://doi.org/10.1073/pnas.2003421117',
    year: 2020,
    reliability: 'Peer-reviewed Meta-analysis',
    confidence: 'High',
    tags: ['deforestation', 'assisted natural regeneration', 'canopy cover', 'keystone species', 'rewilding']
  },
  {
    id: 'KB-FAO-MINILLAGE-10',
    title: 'Conservation Agriculture and Reduced Tillage to Protect Soil Aggregate Stability',
    topic: 'Conservation tillage & Soil fauna preservation',
    environmentalVariables: ['soil organic carbon', 'soil moisture', 'soil health', 'land use'],
    ecosystem: 'Rainfed and irrigated cropping systems',
    region: 'Semi-arid, sub-humid, and Mediterranean agricultural zones',
    condition: 'Conventional deep inversion plowing, frequent soil compaction, crusting, and erosion',
    mechanism: 'Minimal tillage preserves earthworm burrows (macropores), fungal hyphal networks, and structural aggregates, preventing carbon oxidation and reducing wind/water soil loss by up to 80%.',
    expectedEffect: 'Preserves subterranean macro-invertebrate fauna, improves rainwater infiltration rates by 30-50%, and steadily elevates labile carbon in the top 10cm soil layer.',
    timeHorizon: 'Medium term (3-5 years)',
    evidence: 'FAO Conservation Agriculture Technical Factsheets; Pittelkow et al. (2015), Nature: Productivity risks and conservation tillage.',
    source: 'FAO (Food and Agriculture Organization of the United Nations)',
    sourceUrl: 'https://www.fao.org/conservation-agriculture/en/',
    year: 2017,
    reliability: 'Global UN/FAO Assessment',
    confidence: 'High',
    tags: ['conservation agriculture', 'no-till', 'soil macrofauna', 'water infiltration', 'erosion control']
  },
  {
    id: 'KB-IPCC-GRAZING-11',
    title: 'Rotational Grazing and Silvopastoral Integration for Degraded Rangelands',
    topic: 'Rangeland ecology & Pasture biodiversity',
    environmentalVariables: ['land use', 'habitat diversity', 'soil organic carbon', 'species richness', 'rainfall'],
    ecosystem: 'Grasslands, savannas, and shrub rangelands',
    region: 'Arid, semi-arid, and temperate grazing lands',
    condition: 'Continuous overgrazing, unpalatable weed dominance, bare soil patches, low grass diversity',
    mechanism: 'High-density short-duration grazing followed by extended vegetative recovery cycles mimics wild herbivore migration, stimulating root exudation, preventing selective over-browsing, and allowing native perennial tussock grasses to set seed.',
    expectedEffect: 'Revives perennial grass species richness, increases root biomass carbon in deep soil horizons, and restores ground-nesting grassland avian habitats.',
    timeHorizon: 'Medium to Long term (3-8 years)',
    evidence: 'IPCC Climate Change and Land, Chapter 2 (2019); Teague et al. (2016), Journal of Soil and Water Conservation.',
    source: 'IPCC & Society for Range Management',
    sourceUrl: 'https://www.ipcc.ch/srccl/chapter/chapter-2/',
    year: 2019,
    reliability: 'IPCC Assessment Report',
    confidence: 'Medium',
    tags: ['rangelands', 'rotational grazing', 'silvopasture', 'grassland birds', 'root biomass']
  },
  {
    id: 'KB-FAO-MYCORRHIZAE-12',
    title: 'Arbuscular Mycorrhizal Fungi (AMF) Inoculation in Degraded Low-Phosphorus Soils',
    topic: 'Soil microbiology & Plant stress tolerance',
    environmentalVariables: ['soil health', 'soil organic carbon', 'soil pH', 'water availability', 'species richness'],
    ecosystem: 'Degraded drylands, post-mining land, and depleted arable soils',
    region: 'Global arid and nutrient-poor soils',
    condition: 'Depleted fungal-to-bacterial ratio, low available phosphorus, high water stress',
    mechanism: 'Arbuscular mycorrhizal fungal hyphae extend millimeters beyond plant root depletion zones, secreting glomalin (a stable glycoprotein) that binds soil mineral grains into water-stable aggregates while delivering solubilized phosphorus and water under deficit conditions.',
    expectedEffect: 'Enhances seedling survival under water deficit by 20-35% and drives glomalin-related soil carbon accretion.',
    timeHorizon: 'Short to Medium term (1-3 years)',
    evidence: 'FAO Soils Bulletin; Rillig et al. (2019), Trends in Ecology & Evolution.',
    source: 'FAO & Trends in Ecology and Evolution',
    sourceUrl: 'https://www.fao.org/documents/card/en/c/ca7506en/',
    year: 2019,
    reliability: 'Peer-reviewed Meta-analysis',
    confidence: 'High',
    tags: ['mycorrhizae', 'glomalin', 'soil aggregates', 'phosphorus', 'drought tolerance']
  },
  {
    id: 'KB-IPBES-BIODIVCORR-13',
    title: 'Ecological Corridor Stewardship and Keystone Pollinator Monitoring in Resilient Habitats',
    topic: 'Biodiversity conservation & Keystone species connectivity',
    environmentalVariables: ['species richness', 'habitat diversity', 'land use', 'soil organic carbon'],
    ecosystem: 'High-diversity polycultures, native agroforests, and ecological reserves',
    region: 'Humid, sub-humid, and temperate biomes',
    condition: 'High soil organic carbon (>2.5%), multi-tiered vegetation, high baseline species richness',
    mechanism: 'In ecosystems with established structural diversity and high soil organic carbon, ecological function is governed by habitat connectivity and microclimatic stability. Preserving multi-canopy layers and continuous migratory corridors prevents genetic isolation among specialized pollinator guilds and understory avian insectivores.',
    expectedEffect: 'Maintains population stability of wild pollinator assemblages, sustains natural predator-to-prey ratios, and buffers mature carbon stocks against edge-effect desiccation.',
    timeHorizon: 'Medium to Long term (3-10 years)',
    evidence: 'IPBES Global Assessment Report on Biodiversity and Ecosystem Services (2019); Díaz et al. (2019), Science: Pervasive human impacts on global nature.',
    source: 'IPBES (Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services)',
    sourceUrl: 'https://www.ipbes.net/global-assessment',
    year: 2019,
    reliability: 'Global UN/IPBES Assessment',
    confidence: 'High',
    tags: ['keystone species', 'corridors', 'pollinators', 'high carbon', 'resilient ecosystems', 'monitoring']
  },
  {
    id: 'KB-ICRAF-HIGHRAIN-14',
    title: 'Contour Vegetative Hedgerows and Terracing for High-Precipitation Erosion Mitigation',
    topic: 'High rainfall & Soil erosion control',
    environmentalVariables: ['rainfall', 'soil moisture', 'soil health', 'habitat diversity', 'land use'],
    ecosystem: 'Sloping croplands and undulating high-rainfall landscapes (>800mm/yr)',
    region: 'Humid tropical and high-rainfall temperate agricultural zones',
    condition: 'High annual rainfall (>800mm), undulating topography, risk of topsoil rill erosion and nutrient leaching',
    mechanism: 'Dense perennial contour hedgerows (such as deep-rooting native shrubs and vetiver grass) physically retard downslope surface runoff velocities, dissipating hydraulic kinetic energy and forcing the deposition of detached soil sediments behind living vegetative barriers.',
    expectedEffect: 'Reduces topsoil hydraulic erosion losses by 65-85%, mitigates subsoil nitrogen and phosphorus leaching, and establishes micro-terraces that retain organic matter in situ.',
    timeHorizon: 'Short to Medium term (2-4 years)',
    evidence: 'World Agroforestry (ICRAF) Technical Manuals; Blanco & Lal (2010), Principles of Soil Conservation and Management.',
    source: 'World Agroforestry (ICRAF) & Springer',
    sourceUrl: 'https://www.worldagroforestry.org/output/publications',
    year: 2018,
    reliability: 'Peer-reviewed Meta-analysis',
    confidence: 'High',
    tags: ['high rainfall', 'erosion control', 'contour hedgerows', 'terracing', 'nutrient retention']
  },
  {
    id: 'KB-BIOCHAR-ACIDSOIL-15',
    title: 'Pyrogenic Carbon (Biochar) Application for Acidic Soil Remineralization and Cation Exchange',
    topic: 'Soil pH, Acidity & Microbial habitat',
    environmentalVariables: ['soil pH', 'soil organic carbon', 'soil health', 'species richness'],
    ecosystem: 'Acidic, highly weathered agricultural soils (pH < 6.0)',
    region: 'Humid tropics, weathered ultisols/oxisols, and acid temperate soils',
    condition: 'Acidic soil pH (<5.8), low cation exchange capacity (CEC), aluminum toxicity, suppressed microbial biomass',
    mechanism: 'Biochar possesses high surface area, internal micro-porosity, and alkaline surface functional groups. When incorporated into acidic soils, it neutralizes active acidity, complexes toxic exchangeable aluminum ions, and creates protected physical habitats for mycorrhizal fungal hyphae and aerobic bacteria.',
    expectedEffect: 'Raises rhizosphere pH by 0.5-1.2 units, expands effective cation exchange capacity by 20-45%, and increases beneficial bacterial-to-fungal ratios in the root zone.',
    timeHorizon: 'Medium term (2-5 years)',
    evidence: 'Lehmann et al. (2021), Nature Communications: Biochar in climate change mitigation and soil regeneration; FAO Soils Bulletin 94.',
    source: 'Nature Communications & FAO',
    sourceUrl: 'https://doi.org/10.1038/s41467-021-23640-8',
    year: 2021,
    reliability: 'Peer-reviewed Meta-analysis',
    confidence: 'High',
    tags: ['biochar', 'soil pH', 'soil acidity', 'cation exchange', 'microbial habitat']
  }
];
